# Generated by Django 3.0.5 on 2020-09-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200923_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='CQP5HN4PA9', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
