# Generated by Django 3.0.5 on 2020-09-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200924_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='GISCSHXQRL', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
